package com.youedata.cd.industries.dao.building;


import com.youedata.cd.base.dao.IBaseDao;
import com.youedata.cd.industries.pojo.building.BuildingPoint;

public interface BuildingPointMapper extends IBaseDao<BuildingPoint>{
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_building
     *
     * @mbggenerated
     */
    Long deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_building
     *
     * @mbggenerated
     */
    Long insert(BuildingPoint record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_building
     *
     * @mbggenerated
     */
    Long insertSelective(BuildingPoint record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_building
     *
     * @mbggenerated
     */
    BuildingPoint selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_building
     *
     * @mbggenerated
     */
    Long updateByPrimaryKeySelective(BuildingPoint record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_building
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(BuildingPoint record);
}