package com.youedata.cd.industries.dao.enterprise;


import com.youedata.cd.industries.pojo.enterprise.DataVersion;

public interface DataVersionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_data_version
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_data_version
     *
     * @mbggenerated
     */
    int insert(DataVersion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_data_version
     *
     * @mbggenerated
     */
    int insertSelective(DataVersion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_data_version
     *
     * @mbggenerated
     */
    DataVersion selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_data_version
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(DataVersion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_data_version
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(DataVersion record);
}