package com.youedata.cd.industries.pojo.enterprise;

import com.youedata.cd.base.pojo.BaseDomain;
import com.youedata.cd.industries.pojo.category.Category;
import org.apache.commons.lang.StringUtils;

import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;

public class Enterprise {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_enterprise_base.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_enterprise_base.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_enterprise_base.trade_id
     *
     * @mbggenerated
     */
    private Category trade;
    private String address;
    private Double longitude;
    private Double latitude;
    private String sourceLogId;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_enterprise_base.industry_id
     *
     * @mbggenerated
     */
    private Long industryId;
    private String tradeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_enterprise_base.category_id
     *
     * @mbggenerated
     */
    private Long categoryId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_enterprise_base.register_address
     *
     * @mbggenerated
     */
    private String registerAddress;
    private Double registerCapital;
    private String majorBusiness;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_enterprise_base.register_major_business
     *
     * @mbggenerated
     */
    private String registerMajorBusiness;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_enterprise_base.employee_count
     *
     * @mbggenerated
     */
    private String employeeCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_enterprise_base.operate_location
     *
     * @mbggenerated
     */
    private String operateLocation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_enterprise_base.register_location
     *
     * @mbggenerated
     */
    private String registerLocation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_enterprise_base.enterprise_type
     *
     * @mbggenerated
     */
    private String enterpriseType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_enterprise_base.revenue
     *
     * @mbggenerated
     */
    private Double revenue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_enterprise_base.tax
     *
     * @mbggenerated
     */
    private Double tax;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_enterprise_base.register_time
     *
     * @mbggenerated
     */
    private Date registerTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_enterprise_base.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_enterprise_base.linkman
     *
     * @mbggenerated
     */
    private String linkman;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_enterprise_base.phone_number
     *
     * @mbggenerated
     */
    private String phoneNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_enterprise_base.introduce
     *
     * @mbggenerated
     */
    private String introduce;


    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_enterprise_base.open_flag
     *
     * @mbggenerated
     */
    private String openFlag;


    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_enterprise_base.source_log_id
     *
     * @mbggenerated
     */
    private List<EnterpriseLog> sourceLogs;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_enterprise_base.id
     *
     * @return the value of t_enterprise_base.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_enterprise_base.id
     *
     * @param id the value for t_enterprise_base.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_enterprise_base.name
     *
     * @return the value of t_enterprise_base.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_enterprise_base.name
     *
     * @param name the value for t_enterprise_base.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_enterprise_base.trade_id
     *
     * @return the value of t_enterprise_base.trade_id
     *
     * @mbggenerated
     */
    public Category getTrade() {
        return trade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_enterprise_base.trade_id
     *
     * @param trade the value for t_enterprise_base.trade_id
     *
     * @mbggenerated
     */
    public void setTrade(Category trade) {
        this.trade = trade;
    }



    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_enterprise_base.industry_id
     *
     * @return the value of t_enterprise_base.industry_id
     *
     * @mbggenerated
     */
    public Long getIndustryId() {
        return industryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_enterprise_base.industry_id
     *
     * @param industryId the value for t_enterprise_base.industry_id
     *
     * @mbggenerated
     */
    public void setIndustryId(Long industryId) {
        this.industryId = industryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_enterprise_base.category_id
     *
     * @return the value of t_enterprise_base.category_id
     *
     * @mbggenerated
     */
    public Long getCategoryId() {
        return categoryId;
    }

    public String getSourceLogId() {
        return sourceLogId;
    }

    public void setSourceLogId(String sourceLogId) {
        this.sourceLogId = sourceLogId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_enterprise_base.category_id
     *
     * @param categoryId the value for t_enterprise_base.category_id
     *
     * @mbggenerated
     */
    public void setCategoryId(Long categoryId) {
        this.categoryId = categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_enterprise_base.register_address
     *
     * @return the value of t_enterprise_base.register_address
     *
     * @mbggenerated
     */
    public String getRegisterAddress() {
        return registerAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_enterprise_base.register_address
     *
     * @param registerAddress the value for t_enterprise_base.register_address
     *
     * @mbggenerated
     */
    public void setRegisterAddress(String registerAddress) {
        this.registerAddress = registerAddress == null ? null : registerAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_enterprise_base.register_major_business
     *
     * @return the value of t_enterprise_base.register_major_business
     *
     * @mbggenerated
     */
    public String getRegisterMajorBusiness() {
        return registerMajorBusiness;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_enterprise_base.register_major_business
     *
     * @param registerMajorBusiness the value for t_enterprise_base.register_major_business
     *
     * @mbggenerated
     */
    public void setRegisterMajorBusiness(String registerMajorBusiness) {
        this.registerMajorBusiness = registerMajorBusiness == null ? null : registerMajorBusiness.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_enterprise_base.employee_count
     *
     * @return the value of t_enterprise_base.employee_count
     *
     * @mbggenerated
     */
    public String getEmployeeCount() {
        if(StringUtils.isBlank(employeeCount)){
            return "0";
        }
        return employeeCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_enterprise_base.employee_count
     *
     * @param employeeCount the value for t_enterprise_base.employee_count
     *
     * @mbggenerated
     */
    public void setEmployeeCount(String employeeCount) {
        this.employeeCount = employeeCount == null ? null : employeeCount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_enterprise_base.operate_location
     *
     * @return the value of t_enterprise_base.operate_location
     *
     * @mbggenerated
     */
    public String getOperateLocation() {
        return operateLocation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_enterprise_base.operate_location
     *
     * @param operateLocation the value for t_enterprise_base.operate_location
     *
     * @mbggenerated
     */
    public void setOperateLocation(String operateLocation) {
        this.operateLocation = operateLocation == null ? null : operateLocation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_enterprise_base.register_location
     *
     * @return the value of t_enterprise_base.register_location
     *
     * @mbggenerated
     */
    public String getRegisterLocation() {
        return registerLocation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_enterprise_base.register_location
     *
     * @param registerLocation the value for t_enterprise_base.register_location
     *
     * @mbggenerated
     */
    public void setRegisterLocation(String registerLocation) {
        this.registerLocation = registerLocation == null ? null : registerLocation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_enterprise_base.enterprise_type
     *
     * @return the value of t_enterprise_base.enterprise_type
     *
     * @mbggenerated
     */
    public String getEnterpriseType() {
        return enterpriseType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_enterprise_base.enterprise_type
     *
     * @param enterpriseType the value for t_enterprise_base.enterprise_type
     *
     * @mbggenerated
     */
    public void setEnterpriseType(String enterpriseType) {
        this.enterpriseType = enterpriseType == null ? null : enterpriseType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_enterprise_base.revenue
     *
     * @return the value of t_enterprise_base.revenue
     *
     * @mbggenerated
     */
    public Double getRevenue() {
        return revenue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_enterprise_base.revenue
     *
     * @param revenue the value for t_enterprise_base.revenue
     *
     * @mbggenerated
     */
    public void setRevenue(Double revenue) {
        this.revenue = revenue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_enterprise_base.tax
     *
     * @return the value of t_enterprise_base.tax
     *
     * @mbggenerated
     */
    public Double getTax() {
        return tax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_enterprise_base.tax
     *
     * @param tax the value for t_enterprise_base.tax
     *
     * @mbggenerated
     */
    public void setTax(Double tax) {
        this.tax = tax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_enterprise_base.register_time
     *
     * @return the value of t_enterprise_base.register_time
     *
     * @mbggenerated
     */
    public String getRegisterTime() {
        if(registerTime != null){
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            String formatData = sdf.format(registerTime);
            return formatData;

        }else{
            return null;
        }
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_enterprise_base.register_time
     *
     * @param registerTime the value for t_enterprise_base.register_time
     *
     * @mbggenerated
     */
    public void setRegisterTime(Date registerTime) {
        this.registerTime = registerTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_enterprise_base.create_time
     *
     * @return the value of t_enterprise_base.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_enterprise_base.create_time
     *
     * @param createTime the value for t_enterprise_base.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_enterprise_base.linkman
     *
     * @return the value of t_enterprise_base.linkman
     *
     * @mbggenerated
     */
    public String getLinkman() {
        return linkman;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_enterprise_base.linkman
     *
     * @param linkman the value for t_enterprise_base.linkman
     *
     * @mbggenerated
     */
    public void setLinkman(String linkman) {
        this.linkman = linkman == null ? null : linkman.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_enterprise_base.phone_number
     *
     * @return the value of t_enterprise_base.phone_number
     *
     * @mbggenerated
     */
    public String getPhoneNumber() {
        if(StringUtils.isBlank(phoneNumber)){
            return "暂无";
        }
        return phoneNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_enterprise_base.phone_number
     *
     * @param phoneNumber the value for t_enterprise_base.phone_number
     *
     * @mbggenerated
     */
    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber == null ? null : phoneNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_enterprise_base.introduce
     *
     * @return the value of t_enterprise_base.introduce
     *
     * @mbggenerated
     */
    public String getIntroduce() {
        return introduce;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_enterprise_base.introduce
     *
     * @param introduce the value for t_enterprise_base.introduce
     *
     * @mbggenerated
     */
    public void setIntroduce(String introduce) {
        this.introduce = introduce == null ? null : introduce.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_enterprise_base.open_flag
     *
     * @return the value of t_enterprise_base.open_flag
     *
     * @mbggenerated
     */
    public String getOpenFlag() {
//        if(openFlag !=null && openFlag == 0){
//            return "停业";
//        }else if(openFlag !=null && openFlag == 1){
//            return "营业";
//        }else{
//             return "暂无";
//        }
        return openFlag;
    }

    public String getAddress() {
        return address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    public Double getLongitude() {
        return longitude;
    }

    public void setLongitude(Double longitude) {
        this.longitude = longitude;
    }

    public Double getLatitude() {
        return latitude;
    }

    public void setLatitude(Double latitude) {
        this.latitude = latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_enterprise_base.open_flag
     *
     * @param openFlag the value for t_enterprise_base.open_flag
     *
     * @mbggenerated
     */
    public void setOpenFlag(String openFlag) {
        this.openFlag = openFlag;
    }

    public String getTradeName() {
        return tradeName;
    }

    public void setTradeName(String tradeName) {
        this.tradeName = tradeName;
    }

    public String getMajorBusiness() {
        return majorBusiness;
    }

    public void setMajorBusiness(String majorBusiness) {
        this.majorBusiness = majorBusiness;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_enterprise_base.source_log_id
     *
     * @return the value of t_enterprise_base.source_log_id
     *
     * @mbggenerated
     */
    public List<EnterpriseLog> getSourceLogs() {
        return sourceLogs;
    }

    public Double getRegisterCapital() {
        return registerCapital;
    }

    public void setRegisterCapital(Double registerCapital) {
        this.registerCapital = registerCapital;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_enterprise_base.source_log_id
     *
     * @param sourceLogs the value for t_enterprise_base.source_log_id
     *
     * @mbggenerated
     */
    public void setSourceLogs(List<EnterpriseLog> sourceLogs) {
        this.sourceLogs = sourceLogs;
    }


    @Override
    public String toString() {
        return "Enterprise{" +
                "id=" + id +
                ", name='" + name + '\'' +
                ", trade=" + trade +
                ", address='" + address + '\'' +
                ", longitude=" + longitude +
                ", latitude=" + latitude +
                ", industryId=" + industryId +
                ", tradeName='" + tradeName + '\'' +
                ", categoryId=" + categoryId +
                ", registerAddress='" + registerAddress + '\'' +
                ", registerCapital=" + registerCapital +
                ", majorBusiness='" + majorBusiness + '\'' +
                ", registerMajorBusiness='" + registerMajorBusiness + '\'' +
                ", employeeCount='" + employeeCount + '\'' +
                ", operateLocation='" + operateLocation + '\'' +
                ", registerLocation='" + registerLocation + '\'' +
                ", enterpriseType='" + enterpriseType + '\'' +
                ", revenue=" + revenue +
                ", tax=" + tax +
                ", registerTime=" + registerTime +
                ", createTime=" + createTime +
                ", linkman='" + linkman + '\'' +
                ", phoneNumber='" + phoneNumber + '\'' +
                ", introduce='" + introduce + '\'' +
                ", openFlag=" + openFlag +
                ", sourceLogs=" + sourceLogs +
                '}';
    }
}