package com.youedata.cd.industries.pojo.dataversion;

import java.util.Date;

public class DataVersion {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_data_version.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_data_version.version_name
     *
     * @mbggenerated
     */
    private String versionName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_data_version.version_code
     *
     * @mbggenerated
     */
    private String versionCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_data_version.data_type
     *
     * @mbggenerated
     */
    private Integer dataType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_data_version.current_flag
     *
     * @mbggenerated
     */
    private Boolean currentFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_data_version.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_data_version.remark
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_data_version.source_flag
     *
     * @mbggenerated
     */
    private Boolean sourceFlag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_data_version.id
     *
     * @return the value of t_data_version.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_data_version.id
     *
     * @param id the value for t_data_version.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_data_version.version_name
     *
     * @return the value of t_data_version.version_name
     *
     * @mbggenerated
     */
    public String getVersionName() {
        return versionName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_data_version.version_name
     *
     * @param versionName the value for t_data_version.version_name
     *
     * @mbggenerated
     */
    public void setVersionName(String versionName) {
        this.versionName = versionName == null ? null : versionName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_data_version.version_code
     *
     * @return the value of t_data_version.version_code
     *
     * @mbggenerated
     */
    public String getVersionCode() {
        return versionCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_data_version.version_code
     *
     * @param versionCode the value for t_data_version.version_code
     *
     * @mbggenerated
     */
    public void setVersionCode(String versionCode) {
        this.versionCode = versionCode == null ? null : versionCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_data_version.data_type
     *
     * @return the value of t_data_version.data_type
     *
     * @mbggenerated
     */
    public Integer getDataType() {
        return dataType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_data_version.data_type
     *
     * @param dataType the value for t_data_version.data_type
     *
     * @mbggenerated
     */
    public void setDataType(Integer dataType) {
        this.dataType = dataType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_data_version.current_flag
     *
     * @return the value of t_data_version.current_flag
     *
     * @mbggenerated
     */
    public Boolean getCurrentFlag() {
        return currentFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_data_version.current_flag
     *
     * @param currentFlag the value for t_data_version.current_flag
     *
     * @mbggenerated
     */
    public void setCurrentFlag(Boolean currentFlag) {
        this.currentFlag = currentFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_data_version.create_time
     *
     * @return the value of t_data_version.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_data_version.create_time
     *
     * @param createTime the value for t_data_version.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_data_version.remark
     *
     * @return the value of t_data_version.remark
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_data_version.remark
     *
     * @param remark the value for t_data_version.remark
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_data_version.source_flag
     *
     * @return the value of t_data_version.source_flag
     *
     * @mbggenerated
     */
    public Boolean getSourceFlag() {
        return sourceFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_data_version.source_flag
     *
     * @param sourceFlag the value for t_data_version.source_flag
     *
     * @mbggenerated
     */
    public void setSourceFlag(Boolean sourceFlag) {
        this.sourceFlag = sourceFlag;
    }
}