package com.youedata.cd.industries.pojo.community;

import com.youedata.cd.base.pojo.BaseDomain;
import com.youedata.cd.industries.pojo.enterprise.Enterprise;
import com.youedata.cd.industries.pojo.enterprise.EnterpriseResult;

import java.util.ArrayList;
import java.util.List;

public class Community extends BaseDomain {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_community.id
     *
     * @mbggenerated
     */
    private Long id;
    private Integer enterpriseCounts;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_community.name
     *
     * @mbggenerated
     */
    private String name;
    /**
     * 企业一对多外键
     */
    private List<EnterpriseResult> enterprises = new ArrayList();


    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_community.street_id
     *
     * @mbggenerated
     */
    private Long streetId;

    private Double longitude;//经度
    private Double latitude;//纬度

    public Double getLongitude() {
        return longitude;
    }

    public void setLongitude(Double longitude) {
        this.longitude = longitude;
    }

    public Double getLatitude() {
        return latitude;
    }

    public void setLatitude(Double latitude) {
        this.latitude = latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_community.id
     *
     * @return the value of t_community.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_community.id
     *
     * @param id the value for t_community.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_community.name
     *
     * @return the value of t_community.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    public List<EnterpriseResult> getEnterprises() {
        return enterprises;
    }

    public Integer getEnterpriseCounts() {
        return enterpriseCounts;
    }

    public void setEnterpriseCounts(Integer enterpriseCounts) {
        this.enterpriseCounts = enterpriseCounts;
    }

    public void setEnterprises(List<EnterpriseResult> enterprises) {
        this.enterprises = enterprises;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_community.name
     *
     * @param name the value for t_community.name
     *
     * @mbggenerated
     */


    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_community.street_id
     *
     * @return the value of t_community.street_id
     *
     * @mbggenerated
     */

    public Long getStreetId() {
        return streetId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_community.street_id
     *
     * @param streetId the value for t_community.street_id
     *
     * @mbggenerated
     */
    public void setStreetId(Long streetId) {
        this.streetId = streetId;
    }

    @Override
    public String toString() {
        return "Community{" +
                "id=" + id +
                ", enterpriseCounts=" + enterpriseCounts +
                ", name='" + name + '\'' +
                ", enterprises=" + enterprises +
                ", streetId=" + streetId +
                ", longitude=" + longitude +
                ", latitude=" + latitude +
                '}';
    }
}