package com.youedata.cd.industries.pojo.building;

import com.youedata.cd.base.pojo.BaseDomain;
import com.youedata.cd.industries.pojo.enterprise.EnterpriseResult;

import java.sql.Date;
import java.util.ArrayList;
import java.util.List;

public class Building extends BaseDomain {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_building.id
     *
     * @mbggenerated
     */
    private Long id;
    private Integer employeeCounts;
    private Integer enterpriseCounts;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_building.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_building.address
     *
     * @mbggenerated
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_building.longitude
     *
     * @mbggenerated
     */
    private Double longitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_building.latitude
     *
     * @mbggenerated
     */
    private Double latitude;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_building.street_id
     *
     * @mbggenerated
     */
    private Long streetId;

    private Long communityId;

    private Long enterpriseId;

    private String enterpriseName;


    /*序号*/
    private Long number;
    /*楼宇名称*/
    private String buildName;
    /*楼宇地址*/
    private String buildAddress;
    /*所属街道*/
    private String streetName;
    /*所属社区*/
    private String communityName;
    /**注册号**/
    private String registerNumber;

    /*上传时间*/
    private Date uploadDate;

    public Building() {
    }

    public Date getUploadDate() {
        return uploadDate;
    }

    public void setUploadDate(Date uploadDate) {
        this.uploadDate = uploadDate;
    }

    public String getEnterpriseName() {
        return enterpriseName;
    }

    public void setEnterpriseName(String enterpriseName) {
        this.enterpriseName = enterpriseName;
    }

    public Long getEnterpriseId() {
        return enterpriseId;
    }

    public void setEnterpriseId(Long enterpriseId) {
        this.enterpriseId = enterpriseId;
    }

    public Long getNumber() {
        return number;
    }

    public void setNumber(Long number) {
        this.number = number;
    }

    public String getBuildName() {
        return buildName;
    }

    public void setBuildName(String buildName) {
        this.buildName = buildName;
    }

    public String getBuildAddress() {
        return buildAddress;
    }

    public void setBuildAddress(String buildAddress) {
        this.buildAddress = buildAddress;
    }

    public String getStreetName() {
        return streetName;
    }

    public void setStreetName(String streetName) {
        this.streetName = streetName;
    }

    public String getCommunityName() {
        return communityName;
    }

    public void setCommunityName(String communityName) {
        this.communityName = communityName;
    }

    public Long getCommunityId() {
        return communityId;
    }

    public void setCommunityId(Long communityId) {
        this.communityId = communityId;
    }

    /**
     * qiye
     */
    private List<EnterpriseResult> enterprises = new ArrayList<EnterpriseResult>();
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_building.id
     *
     * @return the value of t_building.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_building.id
     *
     * @param id the value for t_building.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_building.name
     *
     * @return the value of t_building.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_building.name
     *
     * @param name the value for t_building.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_building.address
     *
     * @return the value of t_building.address
     *
     * @mbggenerated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_building.address
     *
     * @param address the value for t_building.address
     *
     * @mbggenerated
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_building.longitude
     *
     * @return the value of t_building.longitude
     *
     * @mbggenerated
     */
    public Double getLongitude() {
        return longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_building.longitude
     *
     * @param longitude the value for t_building.longitude
     *
     * @mbggenerated
     */
    public void setLongitude(Double longitude) {
        this.longitude = longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_building.latitude
     *
     * @return the value of t_building.latitude
     *
     * @mbggenerated
     */
    public Double getLatitude() {
        return latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_building.latitude
     *
     * @param latitude the value for t_building.latitude
     *
     * @mbggenerated
     */
    public void setLatitude(Double latitude) {
        this.latitude = latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_building.street_id
     *
     * @return the value of t_building.street_id
     *
     * @mbggenerated
     */
    public Long getStreetId() {
        return streetId;
    }

    public List<EnterpriseResult> getEnterprises() {
        return enterprises;
    }

    public void setEnterprises(List<EnterpriseResult> enterprises) {
        this.enterprises = enterprises;
    }



    public Integer getEmployeeCounts() {
        if(employeeCounts == null){
            return 0;
        }
        return employeeCounts;
    }

    public void setEmployeeCounts(Integer employeeCounts) {
        this.employeeCounts = employeeCounts;
    }

    public Integer getEnterpriseCounts() {
        if(enterpriseCounts == null){
            return 0;
        }
        return enterpriseCounts;
    }

    public void setEnterpriseCounts(Integer enterpriseCounts) {
        this.enterpriseCounts = enterpriseCounts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_building.street_id
     *
     * @param streetId the value for t_building.street_id
     *
     * @mbggenerated
     */

    public void setStreetId(Long streetId) {
        this.streetId = streetId;
    }

    @Override
    public String toString() {
        return "Building{" +
                "id=" + id +
                ", employeeCounts=" + employeeCounts +
                ", enterpriseCounts=" + enterpriseCounts +
                ", name='" + name + '\'' +
                ", address='" + address + '\'' +
                ", longitude=" + longitude +
                ", latitude=" + latitude +
                ", streetId=" + streetId +
                ", communityId=" + communityId +
                ", enterprises=" + enterprises +
                '}';
    }

	public String getRegisterNumber() {
		return registerNumber;
	}

	public void setRegisterNumber(String registerNumber) {
		this.registerNumber = registerNumber;
	}
    
}