package com.youedata.cd.industries.pojo.building;

import com.youedata.cd.base.pojo.BaseDomain;

public class BuildingPoint  extends BaseDomain{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_building.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_building.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_building.address
     *
     * @mbggenerated
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_building.longitude1
     *
     * @mbggenerated
     */
    private Double longitude1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_building.latitude1
     *
     * @mbggenerated
     */
    private Double latitude1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_building.street_id
     *
     * @mbggenerated
     */
    private Integer streetId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_building.longitude2
     *
     * @mbggenerated
     */
    private Double longitude2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_building.latitude2
     *
     * @mbggenerated
     */
    private Double latitude2;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_building.id
     *
     * @return the value of t_building.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_building.id
     *
     * @param id the value for t_building.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_building.name
     *
     * @return the value of t_building.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_building.name
     *
     * @param name the value for t_building.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_building.address
     *
     * @return the value of t_building.address
     *
     * @mbggenerated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_building.address
     *
     * @param address the value for t_building.address
     *
     * @mbggenerated
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_building.longitude1
     *
     * @return the value of t_building.longitude1
     *
     * @mbggenerated
     */
    public Double getLongitude1() {
        return longitude1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_building.longitude1
     *
     * @param longitude1 the value for t_building.longitude1
     *
     * @mbggenerated
     */
    public void setLongitude1(Double longitude1) {
        this.longitude1 = longitude1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_building.latitude1
     *
     * @return the value of t_building.latitude1
     *
     * @mbggenerated
     */
    public Double getLatitude1() {
        return latitude1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_building.latitude1
     *
     * @param latitude1 the value for t_building.latitude1
     *
     * @mbggenerated
     */
    public void setLatitude1(Double latitude1) {
        this.latitude1 = latitude1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_building.street_id
     *
     * @return the value of t_building.street_id
     *
     * @mbggenerated
     */
    public Integer getStreetId() {
        return streetId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_building.street_id
     *
     * @param streetId the value for t_building.street_id
     *
     * @mbggenerated
     */
    public void setStreetId(Integer streetId) {
        this.streetId = streetId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_building.longitude2
     *
     * @return the value of t_building.longitude2
     *
     * @mbggenerated
     */
    public Double getLongitude2() {
        return longitude2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_building.longitude2
     *
     * @param longitude2 the value for t_building.longitude2
     *
     * @mbggenerated
     */
    public void setLongitude2(Double longitude2) {
        this.longitude2 = longitude2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_building.latitude2
     *
     * @return the value of t_building.latitude2
     *
     * @mbggenerated
     */
    public Double getLatitude2() {
        return latitude2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_building.latitude2
     *
     * @param latitude2 the value for t_building.latitude2
     *
     * @mbggenerated
     */
    public void setLatitude2(Double latitude2) {
        this.latitude2 = latitude2;
    }
}